version: '3'

services:
  # MySQL
  # ---
  db:
    container_name: mysql_host
    build:
      context: .
      dockerfile: .mysql.dockerfile
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: charon
      MYSQL_USER: docker
      MYSQL_PASSWORD: docker
      TZ: 'Asia/Tokyo'
    command: mysqld --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci
    ports:
      - 3306:3306

  # phpMyAdmin
  # ---
  phpmyadmin:
    container_name: phpmyadmin_gui
    build:
      context: .
      dockerfile: .phpmyadmin.dockerfile
    environment:
      - PMA_ARBITRARY=1
      - PMA_HOSTS=mysql_host
      - PMA_USER=root
      - PMA_PASSWORD=root
    ports:
      - 6612:80
